package com.aws.analytics.util

import org.slf4j.{Logger, LoggerFactory}
import java.sql.{Connection, DriverManager, PreparedStatement, ResultSet, Statement}
import scala.collection.immutable.Seq
import com.aws.analytics.conf.Config

class HiveUtil() {
    private val logger: Logger = LoggerFactory.getLogger("HiveUtil")

    def getJDBCUrl(conf: Config): String = {
        s"jdbc:hive2://${conf.hiveHost}:10000/${conf.hiveDatabase};"
    }

    def getConnection(conf: Config): Connection = {
        val connectionString = getJDBCUrl(conf)
        println(s"connection string: = ${connectionString}" )
        Class.forName("org.apache.hive.jdbc.HiveDriver")
        DriverManager.getConnection(connectionString, "hadoop", "")
    }

    def queryByJDBC(conf: Config, sql: String) : Seq[String] = {
        var conn: Connection = null
        var ps: PreparedStatement = null
        var rs: ResultSet = null
        var seq: Seq[String] = Seq()
        try {
            conn = getConnection(conf)
            ps = conn.prepareStatement(sql)
            rs = ps.executeQuery

            while (rs.next) {
                seq :+= rs.getString(1)
            }
            seq
        } catch {
            case e: Exception => e.printStackTrace
                seq
        } finally {
            if (rs != null) rs.close
            if (ps != null) ps.close
            if (conn != null) conn.close
        }
    }

    def execByJDBC(conf: Config, sql: String) : Boolean = {
        var conn: Connection = null
        var stat: Statement = null

        try {
            conn = getConnection(conf)
            stat = conn.createStatement()
            stat.execute(sql)
            true
        } catch {
            case e: Exception => e.printStackTrace
                false
        } finally {
            if (stat != null) stat.close
            if (conn != null) conn.close
        }
    }

    def msckRepairTable(conf: Config, tableName: String): Unit = {
        val conn = getConnection(conf)
        val stmt = conn.createStatement
        stmt.execute(s"msck repair table ${tableName}")
        stmt.close()
    }

    def getCreateTableString(td: TableDetails, conf: Config, tableName: String): (String, Option[String]) = {
        // the partition column in RDS is last_update_time with value like : 2023-10-17 12:33:19, but in Hive we use pt.

        // check the columns contains pt as partition key.
        val partitonPt : DBField = DBField("last_update_time", "TIMESTAMP", None)

        var partitionKeys = scala.collection.immutable.Set[String]()
        var partitionStr = ""

        if (td.validFields.contains(partitonPt)) {
            partitionKeys = partitionKeys + "pt"
            partitionStr = "PARTITIONED BY (pt STRING)"
        } else {
            partitionStr = ""
        }

        val retPartitionKeys: Option[String] =
            if (partitionKeys.size == 1)  {
                Some(partitionKeys.toSeq.head)
            } else {
                None
            }

        val fieldsInCreateTable = td.validFields.map(r => s"""\t${r.fieldName.toLowerCase} ${r.fieldType} """).mkString(",\n")

        val createTableScipt =
            s"""CREATE EXTERNAL TABLE if not exists ${conf.hiveDatabase}.${tableName} (
               |    $fieldsInCreateTable
               |) ${partitionStr}
               | stored as parquet
               | location '${conf.hiveTablePath}/${conf.hiveDatabase}/$tableName'
               | tblproperties('comment' = 'generated by script',
               | 'owner' = '',
               | 'parquet.compression' = 'SNAPPY')""".stripMargin

        (createTableScipt, retPartitionKeys)
    }

    def generateAuditSQL(conf: Config, tableName: String): String = {
        logger.info(s"************************ tableName: ${tableName}")
        val conn = getConnection(conf)
        val stmt = conn.createStatement()
        val query = s"SELECT * from `${conf.hiveDatabase}`.`${tableName}` where 1 < 0"
        val rs = stmt.executeQuery(query)
        val rsmd = rs.getMetaData

        val auditFieldTypes = Set("TINYINT", "SMALLINT", "INT", "BIGINT", "FLOAT", "DOUBLE")
        var auditFields = Seq[String]()

        logger.info(s"************************ getColumnCount: ${rsmd.getColumnCount}")
        for (i <- 1 to rsmd.getColumnCount) {
            val columnType = rsmd.getColumnTypeName(i)

            if (auditFieldTypes.contains(columnType.toUpperCase))
                auditFields = auditFields :+ rsmd.getColumnName(i)
        }

        var auditSQL = "select " + auditFields.map(r => s" sum(${r.toLowerCase}) ").mkString(", ") + s" from `${conf.hiveDatabase}`.`${tableName}` "

        // check whether the table has partition
        val rspar = stmt.executeQuery(s"SHOW PARTITIONS `${conf.hiveDatabase}`.`${tableName}`")
        if (rspar.next())
            auditSQL += s" where ${conf.hiveFilter}"

        stmt.close()
        conn.close()

        auditSQL
    }
}
